In [1]:
import numpy as np

In [16]:
arr1=np.array([[4,5],
              [6,7]])
print(arr1)
arr2=np.array([[0,1],
              [2,3]])
print(arr2)
print('Vertically\n',np.vstack((arr1,arr2)))
print('Horizontally\n',np.hstack((arr1,arr2)))

[[4 5]
 [6 7]]
[[0 1]
 [2 3]]
Vertically
 [[4 5]
 [6 7]
 [0 1]
 [2 3]]
Horizontally
 [[4 5 0 1]
 [6 7 2 3]]
