In [1]:
import numpy as np

In [11]:
l1=[]
for i in range(0,5):
    n=int(input())
    l1.append(n)
print(l1)
l2=[]
for j in range(0,5):
    m=int(input())
    l2.append(m)
print(l2)
arr1=np.array(l1)
print(arr1)
arr2=np.array(l2)
print(arr2)
arr=np.concatenate((arr1,arr2), axis=None)
print(arr)
print(np.sort(arr))

1
2
3
4
5
[1, 2, 3, 4, 5]
1
2
3
4
5
[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5 1 2 3 4 5]
[1 1 2 2 3 3 4 4 5 5]
